server:
  port: 8401

spring:
  application:
    name: cloudalibab-sentinel-service

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.255.10:8848

    sentinel:
      transport:
        dashboard: localhost:8080
        # 默认8719端口，如被占用，自动从8719开始依次+1扫描，直至找到违背占用的端口
        port: 8719
      # sentinel持久化配置
      datasource:
        ds1:
          nacos:
            server-addr: 192.168.255.10:8848
            dataId: ${spring.application.name}
            groupId: DEFAULT_GROUP
            data_type: json
            rule_type: flow

management:
  endpoints:
    web:
      exposure:
        include: '*'

