server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  # zipkin 配置
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1 # 采样率介于0~1之间，1 表示全部采集

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource      #当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver        #mysql驱动包
    url: jdbc:mysql://192.168.255.10:3306/acdb?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ac.springcloud.entity       #所有Entity别名类所在包

eureka:
  client:
    # 向Eureka Server服务中心注册自己
    register-with-eureka: true
    # 是否从Eureka Server抓取已有的注册信息，集群必须设置为true，才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: payment8001 #eureka服务界面显示的服务名称
    prefer-ip-address: true # 显示ip