server:
  port: 83

spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.255.10:8848

# 服务提供者服务名称
server-url:
  nacos-user-service: http://nacos-payment-provider