server:
  port: 80

eureka:
  client:
    # 向Eureka Server服务中心注册自己
    register-with-eureka: false
    # 是否从Eureka Server抓取已有的注册信息，集群必须设置为true，才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

# 设置feign客户端超时时间
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000

logging:
  level:
    com.ac.springcloud.service.PaymentFeignService: debug
